# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/vladoo/coding/ci/vtl

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/vladoo/coding/ci/vtl

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/Applications/CMake.app/Contents/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/Applications/CMake.app/Contents/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vladoo/coding/ci/vtl/CMakeFiles /Users/vladoo/coding/ci/vtl//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/vladoo/coding/ci/vtl/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VTL

# Build rule for target.
VTL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VTL
.PHONY : VTL

# fast build rule for target.
VTL/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/build
.PHONY : VTL/fast

#=============================================================================
# Target rules for targets named VTL_img

# Build rule for target.
VTL_img: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VTL_img
.PHONY : VTL_img

# fast build rule for target.
VTL_img/fast:
	$(MAKE) $(MAKESILENT) -f VTL/media_container/img/CMakeFiles/VTL_img.dir/build.make VTL/media_container/img/CMakeFiles/VTL_img.dir/build
.PHONY : VTL_img/fast

#=============================================================================
# Target rules for targets named VTL_tests_Audio

# Build rule for target.
VTL_tests_Audio: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 VTL_tests_Audio
.PHONY : VTL_tests_Audio

# fast build rule for target.
VTL_tests_Audio/fast:
	$(MAKE) $(MAKESILENT) -f vtl_tests/audio/CMakeFiles/VTL_tests_Audio.dir/build.make vtl_tests/audio/CMakeFiles/VTL_tests_Audio.dir/build
.PHONY : VTL_tests_Audio/fast

VTL/content_platform/VTL_content_platform_flags_check.o: VTL/content_platform/VTL_content_platform_flags_check.c.o
.PHONY : VTL/content_platform/VTL_content_platform_flags_check.o

# target to build an object file
VTL/content_platform/VTL_content_platform_flags_check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/VTL_content_platform_flags_check.c.o
.PHONY : VTL/content_platform/VTL_content_platform_flags_check.c.o

VTL/content_platform/VTL_content_platform_flags_check.i: VTL/content_platform/VTL_content_platform_flags_check.c.i
.PHONY : VTL/content_platform/VTL_content_platform_flags_check.i

# target to preprocess a source file
VTL/content_platform/VTL_content_platform_flags_check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/VTL_content_platform_flags_check.c.i
.PHONY : VTL/content_platform/VTL_content_platform_flags_check.c.i

VTL/content_platform/VTL_content_platform_flags_check.s: VTL/content_platform/VTL_content_platform_flags_check.c.s
.PHONY : VTL/content_platform/VTL_content_platform_flags_check.s

# target to generate assembly for a file
VTL/content_platform/VTL_content_platform_flags_check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/VTL_content_platform_flags_check.c.s
.PHONY : VTL/content_platform/VTL_content_platform_flags_check.c.s

VTL/content_platform/VTL_content_platform_publication.o: VTL/content_platform/VTL_content_platform_publication.c.o
.PHONY : VTL/content_platform/VTL_content_platform_publication.o

# target to build an object file
VTL/content_platform/VTL_content_platform_publication.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/VTL_content_platform_publication.c.o
.PHONY : VTL/content_platform/VTL_content_platform_publication.c.o

VTL/content_platform/VTL_content_platform_publication.i: VTL/content_platform/VTL_content_platform_publication.c.i
.PHONY : VTL/content_platform/VTL_content_platform_publication.i

# target to preprocess a source file
VTL/content_platform/VTL_content_platform_publication.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/VTL_content_platform_publication.c.i
.PHONY : VTL/content_platform/VTL_content_platform_publication.c.i

VTL/content_platform/VTL_content_platform_publication.s: VTL/content_platform/VTL_content_platform_publication.c.s
.PHONY : VTL/content_platform/VTL_content_platform_publication.s

# target to generate assembly for a file
VTL/content_platform/VTL_content_platform_publication.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/VTL_content_platform_publication.c.s
.PHONY : VTL/content_platform/VTL_content_platform_publication.c.s

VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.o: VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.o
.PHONY : VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.o

# target to build an object file
VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.o
.PHONY : VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.o

VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.i: VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.i
.PHONY : VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.i

# target to preprocess a source file
VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.i
.PHONY : VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.i

VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.s: VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.s
.PHONY : VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.s

# target to generate assembly for a file
VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.s
.PHONY : VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.c.s

VTL/content_platform/infra/audio/VTL_audio_gen.o: VTL/content_platform/infra/audio/VTL_audio_gen.c.o
.PHONY : VTL/content_platform/infra/audio/VTL_audio_gen.o

# target to build an object file
VTL/content_platform/infra/audio/VTL_audio_gen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/audio/VTL_audio_gen.c.o
.PHONY : VTL/content_platform/infra/audio/VTL_audio_gen.c.o

VTL/content_platform/infra/audio/VTL_audio_gen.i: VTL/content_platform/infra/audio/VTL_audio_gen.c.i
.PHONY : VTL/content_platform/infra/audio/VTL_audio_gen.i

# target to preprocess a source file
VTL/content_platform/infra/audio/VTL_audio_gen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/audio/VTL_audio_gen.c.i
.PHONY : VTL/content_platform/infra/audio/VTL_audio_gen.c.i

VTL/content_platform/infra/audio/VTL_audio_gen.s: VTL/content_platform/infra/audio/VTL_audio_gen.c.s
.PHONY : VTL/content_platform/infra/audio/VTL_audio_gen.s

# target to generate assembly for a file
VTL/content_platform/infra/audio/VTL_audio_gen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/audio/VTL_audio_gen.c.s
.PHONY : VTL/content_platform/infra/audio/VTL_audio_gen.c.s

VTL/content_platform/infra/text/VTL_publication_text_gen.o: VTL/content_platform/infra/text/VTL_publication_text_gen.c.o
.PHONY : VTL/content_platform/infra/text/VTL_publication_text_gen.o

# target to build an object file
VTL/content_platform/infra/text/VTL_publication_text_gen.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/text/VTL_publication_text_gen.c.o
.PHONY : VTL/content_platform/infra/text/VTL_publication_text_gen.c.o

VTL/content_platform/infra/text/VTL_publication_text_gen.i: VTL/content_platform/infra/text/VTL_publication_text_gen.c.i
.PHONY : VTL/content_platform/infra/text/VTL_publication_text_gen.i

# target to preprocess a source file
VTL/content_platform/infra/text/VTL_publication_text_gen.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/text/VTL_publication_text_gen.c.i
.PHONY : VTL/content_platform/infra/text/VTL_publication_text_gen.c.i

VTL/content_platform/infra/text/VTL_publication_text_gen.s: VTL/content_platform/infra/text/VTL_publication_text_gen.c.s
.PHONY : VTL/content_platform/infra/text/VTL_publication_text_gen.s

# target to generate assembly for a file
VTL/content_platform/infra/text/VTL_publication_text_gen.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/text/VTL_publication_text_gen.c.s
.PHONY : VTL/content_platform/infra/text/VTL_publication_text_gen.c.s

VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.o: VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.o
.PHONY : VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.o

# target to build an object file
VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.o
.PHONY : VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.o

VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.i: VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.i
.PHONY : VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.i

# target to preprocess a source file
VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.i
.PHONY : VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.i

VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.s: VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.s
.PHONY : VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.s

# target to generate assembly for a file
VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.s
.PHONY : VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.c.s

VTL/content_platform/tg/VTL_content_platform_tg_net.o: VTL/content_platform/tg/VTL_content_platform_tg_net.c.o
.PHONY : VTL/content_platform/tg/VTL_content_platform_tg_net.o

# target to build an object file
VTL/content_platform/tg/VTL_content_platform_tg_net.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/VTL_content_platform_tg_net.c.o
.PHONY : VTL/content_platform/tg/VTL_content_platform_tg_net.c.o

VTL/content_platform/tg/VTL_content_platform_tg_net.i: VTL/content_platform/tg/VTL_content_platform_tg_net.c.i
.PHONY : VTL/content_platform/tg/VTL_content_platform_tg_net.i

# target to preprocess a source file
VTL/content_platform/tg/VTL_content_platform_tg_net.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/VTL_content_platform_tg_net.c.i
.PHONY : VTL/content_platform/tg/VTL_content_platform_tg_net.c.i

VTL/content_platform/tg/VTL_content_platform_tg_net.s: VTL/content_platform/tg/VTL_content_platform_tg_net.c.s
.PHONY : VTL/content_platform/tg/VTL_content_platform_tg_net.s

# target to generate assembly for a file
VTL/content_platform/tg/VTL_content_platform_tg_net.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/VTL_content_platform_tg_net.c.s
.PHONY : VTL/content_platform/tg/VTL_content_platform_tg_net.c.s

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.o: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.o
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.o

# target to build an object file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.o
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.o

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.i: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.i
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.i

# target to preprocess a source file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.i
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.i

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.s: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.s
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.s

# target to generate assembly for a file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.s
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.c.s

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.o: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.o
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.o

# target to build an object file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.o
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.o

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.i: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.i
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.i

# target to preprocess a source file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.i
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.i

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.s: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.s
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.s

# target to generate assembly for a file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.s
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.c.s

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.o: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.o
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.o

# target to build an object file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.o
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.o

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.i: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.i
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.i

# target to preprocess a source file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.i
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.i

VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.s: VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.s
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.s

# target to generate assembly for a file
VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.s
.PHONY : VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.c.s

VTL/media_container/audio/VTL_audio_data.o: VTL/media_container/audio/VTL_audio_data.c.o
.PHONY : VTL/media_container/audio/VTL_audio_data.o

# target to build an object file
VTL/media_container/audio/VTL_audio_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/VTL_audio_data.c.o
.PHONY : VTL/media_container/audio/VTL_audio_data.c.o

VTL/media_container/audio/VTL_audio_data.i: VTL/media_container/audio/VTL_audio_data.c.i
.PHONY : VTL/media_container/audio/VTL_audio_data.i

# target to preprocess a source file
VTL/media_container/audio/VTL_audio_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/VTL_audio_data.c.i
.PHONY : VTL/media_container/audio/VTL_audio_data.c.i

VTL/media_container/audio/VTL_audio_data.s: VTL/media_container/audio/VTL_audio_data.c.s
.PHONY : VTL/media_container/audio/VTL_audio_data.s

# target to generate assembly for a file
VTL/media_container/audio/VTL_audio_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/VTL_audio_data.c.s
.PHONY : VTL/media_container/audio/VTL_audio_data.c.s

VTL/media_container/audio/infra/VTL_audio_read.o: VTL/media_container/audio/infra/VTL_audio_read.c.o
.PHONY : VTL/media_container/audio/infra/VTL_audio_read.o

# target to build an object file
VTL/media_container/audio/infra/VTL_audio_read.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/infra/VTL_audio_read.c.o
.PHONY : VTL/media_container/audio/infra/VTL_audio_read.c.o

VTL/media_container/audio/infra/VTL_audio_read.i: VTL/media_container/audio/infra/VTL_audio_read.c.i
.PHONY : VTL/media_container/audio/infra/VTL_audio_read.i

# target to preprocess a source file
VTL/media_container/audio/infra/VTL_audio_read.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/infra/VTL_audio_read.c.i
.PHONY : VTL/media_container/audio/infra/VTL_audio_read.c.i

VTL/media_container/audio/infra/VTL_audio_read.s: VTL/media_container/audio/infra/VTL_audio_read.c.s
.PHONY : VTL/media_container/audio/infra/VTL_audio_read.s

# target to generate assembly for a file
VTL/media_container/audio/infra/VTL_audio_read.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/infra/VTL_audio_read.c.s
.PHONY : VTL/media_container/audio/infra/VTL_audio_read.c.s

VTL/media_container/audio/infra/VTL_audio_write.o: VTL/media_container/audio/infra/VTL_audio_write.c.o
.PHONY : VTL/media_container/audio/infra/VTL_audio_write.o

# target to build an object file
VTL/media_container/audio/infra/VTL_audio_write.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/infra/VTL_audio_write.c.o
.PHONY : VTL/media_container/audio/infra/VTL_audio_write.c.o

VTL/media_container/audio/infra/VTL_audio_write.i: VTL/media_container/audio/infra/VTL_audio_write.c.i
.PHONY : VTL/media_container/audio/infra/VTL_audio_write.i

# target to preprocess a source file
VTL/media_container/audio/infra/VTL_audio_write.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/infra/VTL_audio_write.c.i
.PHONY : VTL/media_container/audio/infra/VTL_audio_write.c.i

VTL/media_container/audio/infra/VTL_audio_write.s: VTL/media_container/audio/infra/VTL_audio_write.c.s
.PHONY : VTL/media_container/audio/infra/VTL_audio_write.s

# target to generate assembly for a file
VTL/media_container/audio/infra/VTL_audio_write.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/audio/infra/VTL_audio_write.c.s
.PHONY : VTL/media_container/audio/infra/VTL_audio_write.c.s

VTL/media_container/img/VTL_img_core.o: VTL/media_container/img/VTL_img_core.c.o
.PHONY : VTL/media_container/img/VTL_img_core.o

# target to build an object file
VTL/media_container/img/VTL_img_core.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_core.c.o
.PHONY : VTL/media_container/img/VTL_img_core.c.o

VTL/media_container/img/VTL_img_core.i: VTL/media_container/img/VTL_img_core.c.i
.PHONY : VTL/media_container/img/VTL_img_core.i

# target to preprocess a source file
VTL/media_container/img/VTL_img_core.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_core.c.i
.PHONY : VTL/media_container/img/VTL_img_core.c.i

VTL/media_container/img/VTL_img_core.s: VTL/media_container/img/VTL_img_core.c.s
.PHONY : VTL/media_container/img/VTL_img_core.s

# target to generate assembly for a file
VTL/media_container/img/VTL_img_core.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_core.c.s
.PHONY : VTL/media_container/img/VTL_img_core.c.s

VTL/media_container/img/VTL_img_filters.o: VTL/media_container/img/VTL_img_filters.c.o
.PHONY : VTL/media_container/img/VTL_img_filters.o

# target to build an object file
VTL/media_container/img/VTL_img_filters.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_filters.c.o
.PHONY : VTL/media_container/img/VTL_img_filters.c.o

VTL/media_container/img/VTL_img_filters.i: VTL/media_container/img/VTL_img_filters.c.i
.PHONY : VTL/media_container/img/VTL_img_filters.i

# target to preprocess a source file
VTL/media_container/img/VTL_img_filters.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_filters.c.i
.PHONY : VTL/media_container/img/VTL_img_filters.c.i

VTL/media_container/img/VTL_img_filters.s: VTL/media_container/img/VTL_img_filters.c.s
.PHONY : VTL/media_container/img/VTL_img_filters.s

# target to generate assembly for a file
VTL/media_container/img/VTL_img_filters.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_filters.c.s
.PHONY : VTL/media_container/img/VTL_img_filters.c.s

VTL/media_container/img/VTL_img_utils.o: VTL/media_container/img/VTL_img_utils.c.o
.PHONY : VTL/media_container/img/VTL_img_utils.o

# target to build an object file
VTL/media_container/img/VTL_img_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_utils.c.o
.PHONY : VTL/media_container/img/VTL_img_utils.c.o

VTL/media_container/img/VTL_img_utils.i: VTL/media_container/img/VTL_img_utils.c.i
.PHONY : VTL/media_container/img/VTL_img_utils.i

# target to preprocess a source file
VTL/media_container/img/VTL_img_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_utils.c.i
.PHONY : VTL/media_container/img/VTL_img_utils.c.i

VTL/media_container/img/VTL_img_utils.s: VTL/media_container/img/VTL_img_utils.c.s
.PHONY : VTL/media_container/img/VTL_img_utils.s

# target to generate assembly for a file
VTL/media_container/img/VTL_img_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/img/VTL_img_utils.c.s
.PHONY : VTL/media_container/img/VTL_img_utils.c.s

VTL/media_container/video/VTL_video_data.o: VTL/media_container/video/VTL_video_data.c.o
.PHONY : VTL/media_container/video/VTL_video_data.o

# target to build an object file
VTL/media_container/video/VTL_video_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/video/VTL_video_data.c.o
.PHONY : VTL/media_container/video/VTL_video_data.c.o

VTL/media_container/video/VTL_video_data.i: VTL/media_container/video/VTL_video_data.c.i
.PHONY : VTL/media_container/video/VTL_video_data.i

# target to preprocess a source file
VTL/media_container/video/VTL_video_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/video/VTL_video_data.c.i
.PHONY : VTL/media_container/video/VTL_video_data.c.i

VTL/media_container/video/VTL_video_data.s: VTL/media_container/video/VTL_video_data.c.s
.PHONY : VTL/media_container/video/VTL_video_data.s

# target to generate assembly for a file
VTL/media_container/video/VTL_video_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/media_container/video/VTL_video_data.c.s
.PHONY : VTL/media_container/video/VTL_video_data.c.s

VTL/publication/VTL_publication.o: VTL/publication/VTL_publication.c.o
.PHONY : VTL/publication/VTL_publication.o

# target to build an object file
VTL/publication/VTL_publication.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/VTL_publication.c.o
.PHONY : VTL/publication/VTL_publication.c.o

VTL/publication/VTL_publication.i: VTL/publication/VTL_publication.c.i
.PHONY : VTL/publication/VTL_publication.i

# target to preprocess a source file
VTL/publication/VTL_publication.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/VTL_publication.c.i
.PHONY : VTL/publication/VTL_publication.c.i

VTL/publication/VTL_publication.s: VTL/publication/VTL_publication.c.s
.PHONY : VTL/publication/VTL_publication.s

# target to generate assembly for a file
VTL/publication/VTL_publication.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/VTL_publication.c.s
.PHONY : VTL/publication/VTL_publication.c.s

VTL/publication/text/VTL_publication_markup_text_flags_check.o: VTL/publication/text/VTL_publication_markup_text_flags_check.c.o
.PHONY : VTL/publication/text/VTL_publication_markup_text_flags_check.o

# target to build an object file
VTL/publication/text/VTL_publication_markup_text_flags_check.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_markup_text_flags_check.c.o
.PHONY : VTL/publication/text/VTL_publication_markup_text_flags_check.c.o

VTL/publication/text/VTL_publication_markup_text_flags_check.i: VTL/publication/text/VTL_publication_markup_text_flags_check.c.i
.PHONY : VTL/publication/text/VTL_publication_markup_text_flags_check.i

# target to preprocess a source file
VTL/publication/text/VTL_publication_markup_text_flags_check.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_markup_text_flags_check.c.i
.PHONY : VTL/publication/text/VTL_publication_markup_text_flags_check.c.i

VTL/publication/text/VTL_publication_markup_text_flags_check.s: VTL/publication/text/VTL_publication_markup_text_flags_check.c.s
.PHONY : VTL/publication/text/VTL_publication_markup_text_flags_check.s

# target to generate assembly for a file
VTL/publication/text/VTL_publication_markup_text_flags_check.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_markup_text_flags_check.c.s
.PHONY : VTL/publication/text/VTL_publication_markup_text_flags_check.c.s

VTL/publication/text/VTL_publication_text_data.o: VTL/publication/text/VTL_publication_text_data.c.o
.PHONY : VTL/publication/text/VTL_publication_text_data.o

# target to build an object file
VTL/publication/text/VTL_publication_text_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_text_data.c.o
.PHONY : VTL/publication/text/VTL_publication_text_data.c.o

VTL/publication/text/VTL_publication_text_data.i: VTL/publication/text/VTL_publication_text_data.c.i
.PHONY : VTL/publication/text/VTL_publication_text_data.i

# target to preprocess a source file
VTL/publication/text/VTL_publication_text_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_text_data.c.i
.PHONY : VTL/publication/text/VTL_publication_text_data.c.i

VTL/publication/text/VTL_publication_text_data.s: VTL/publication/text/VTL_publication_text_data.c.s
.PHONY : VTL/publication/text/VTL_publication_text_data.s

# target to generate assembly for a file
VTL/publication/text/VTL_publication_text_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_text_data.c.s
.PHONY : VTL/publication/text/VTL_publication_text_data.c.s

VTL/publication/text/VTL_publication_text_op.o: VTL/publication/text/VTL_publication_text_op.c.o
.PHONY : VTL/publication/text/VTL_publication_text_op.o

# target to build an object file
VTL/publication/text/VTL_publication_text_op.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_text_op.c.o
.PHONY : VTL/publication/text/VTL_publication_text_op.c.o

VTL/publication/text/VTL_publication_text_op.i: VTL/publication/text/VTL_publication_text_op.c.i
.PHONY : VTL/publication/text/VTL_publication_text_op.i

# target to preprocess a source file
VTL/publication/text/VTL_publication_text_op.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_text_op.c.i
.PHONY : VTL/publication/text/VTL_publication_text_op.c.i

VTL/publication/text/VTL_publication_text_op.s: VTL/publication/text/VTL_publication_text_op.c.s
.PHONY : VTL/publication/text/VTL_publication_text_op.s

# target to generate assembly for a file
VTL/publication/text/VTL_publication_text_op.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/VTL_publication_text_op.c.s
.PHONY : VTL/publication/text/VTL_publication_text_op.c.s

VTL/publication/text/infra/VTL_publication_text_read.o: VTL/publication/text/infra/VTL_publication_text_read.c.o
.PHONY : VTL/publication/text/infra/VTL_publication_text_read.o

# target to build an object file
VTL/publication/text/infra/VTL_publication_text_read.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/infra/VTL_publication_text_read.c.o
.PHONY : VTL/publication/text/infra/VTL_publication_text_read.c.o

VTL/publication/text/infra/VTL_publication_text_read.i: VTL/publication/text/infra/VTL_publication_text_read.c.i
.PHONY : VTL/publication/text/infra/VTL_publication_text_read.i

# target to preprocess a source file
VTL/publication/text/infra/VTL_publication_text_read.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/infra/VTL_publication_text_read.c.i
.PHONY : VTL/publication/text/infra/VTL_publication_text_read.c.i

VTL/publication/text/infra/VTL_publication_text_read.s: VTL/publication/text/infra/VTL_publication_text_read.c.s
.PHONY : VTL/publication/text/infra/VTL_publication_text_read.s

# target to generate assembly for a file
VTL/publication/text/infra/VTL_publication_text_read.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/infra/VTL_publication_text_read.c.s
.PHONY : VTL/publication/text/infra/VTL_publication_text_read.c.s

VTL/publication/text/infra/VTL_publication_text_write.o: VTL/publication/text/infra/VTL_publication_text_write.c.o
.PHONY : VTL/publication/text/infra/VTL_publication_text_write.o

# target to build an object file
VTL/publication/text/infra/VTL_publication_text_write.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/infra/VTL_publication_text_write.c.o
.PHONY : VTL/publication/text/infra/VTL_publication_text_write.c.o

VTL/publication/text/infra/VTL_publication_text_write.i: VTL/publication/text/infra/VTL_publication_text_write.c.i
.PHONY : VTL/publication/text/infra/VTL_publication_text_write.i

# target to preprocess a source file
VTL/publication/text/infra/VTL_publication_text_write.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/infra/VTL_publication_text_write.c.i
.PHONY : VTL/publication/text/infra/VTL_publication_text_write.c.i

VTL/publication/text/infra/VTL_publication_text_write.s: VTL/publication/text/infra/VTL_publication_text_write.c.s
.PHONY : VTL/publication/text/infra/VTL_publication_text_write.s

# target to generate assembly for a file
VTL/publication/text/infra/VTL_publication_text_write.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/publication/text/infra/VTL_publication_text_write.c.s
.PHONY : VTL/publication/text/infra/VTL_publication_text_write.c.s

VTL/user/VTL_user_data.o: VTL/user/VTL_user_data.c.o
.PHONY : VTL/user/VTL_user_data.o

# target to build an object file
VTL/user/VTL_user_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/VTL_user_data.c.o
.PHONY : VTL/user/VTL_user_data.c.o

VTL/user/VTL_user_data.i: VTL/user/VTL_user_data.c.i
.PHONY : VTL/user/VTL_user_data.i

# target to preprocess a source file
VTL/user/VTL_user_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/VTL_user_data.c.i
.PHONY : VTL/user/VTL_user_data.c.i

VTL/user/VTL_user_data.s: VTL/user/VTL_user_data.c.s
.PHONY : VTL/user/VTL_user_data.s

# target to generate assembly for a file
VTL/user/VTL_user_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/VTL_user_data.c.s
.PHONY : VTL/user/VTL_user_data.c.s

VTL/user/history/VTL_user_history_data.o: VTL/user/history/VTL_user_history_data.c.o
.PHONY : VTL/user/history/VTL_user_history_data.o

# target to build an object file
VTL/user/history/VTL_user_history_data.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/history/VTL_user_history_data.c.o
.PHONY : VTL/user/history/VTL_user_history_data.c.o

VTL/user/history/VTL_user_history_data.i: VTL/user/history/VTL_user_history_data.c.i
.PHONY : VTL/user/history/VTL_user_history_data.i

# target to preprocess a source file
VTL/user/history/VTL_user_history_data.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/history/VTL_user_history_data.c.i
.PHONY : VTL/user/history/VTL_user_history_data.c.i

VTL/user/history/VTL_user_history_data.s: VTL/user/history/VTL_user_history_data.c.s
.PHONY : VTL/user/history/VTL_user_history_data.s

# target to generate assembly for a file
VTL/user/history/VTL_user_history_data.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/history/VTL_user_history_data.c.s
.PHONY : VTL/user/history/VTL_user_history_data.c.s

VTL/user/history/db/VTL_user_history_save.o: VTL/user/history/db/VTL_user_history_save.c.o
.PHONY : VTL/user/history/db/VTL_user_history_save.o

# target to build an object file
VTL/user/history/db/VTL_user_history_save.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/history/db/VTL_user_history_save.c.o
.PHONY : VTL/user/history/db/VTL_user_history_save.c.o

VTL/user/history/db/VTL_user_history_save.i: VTL/user/history/db/VTL_user_history_save.c.i
.PHONY : VTL/user/history/db/VTL_user_history_save.i

# target to preprocess a source file
VTL/user/history/db/VTL_user_history_save.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/history/db/VTL_user_history_save.c.i
.PHONY : VTL/user/history/db/VTL_user_history_save.c.i

VTL/user/history/db/VTL_user_history_save.s: VTL/user/history/db/VTL_user_history_save.c.s
.PHONY : VTL/user/history/db/VTL_user_history_save.s

# target to generate assembly for a file
VTL/user/history/db/VTL_user_history_save.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/user/history/db/VTL_user_history_save.c.s
.PHONY : VTL/user/history/db/VTL_user_history_save.c.s

VTL/utils/VTL_encryptor.o: VTL/utils/VTL_encryptor.c.o
.PHONY : VTL/utils/VTL_encryptor.o

# target to build an object file
VTL/utils/VTL_encryptor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_encryptor.c.o
.PHONY : VTL/utils/VTL_encryptor.c.o

VTL/utils/VTL_encryptor.i: VTL/utils/VTL_encryptor.c.i
.PHONY : VTL/utils/VTL_encryptor.i

# target to preprocess a source file
VTL/utils/VTL_encryptor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_encryptor.c.i
.PHONY : VTL/utils/VTL_encryptor.c.i

VTL/utils/VTL_encryptor.s: VTL/utils/VTL_encryptor.c.s
.PHONY : VTL/utils/VTL_encryptor.s

# target to generate assembly for a file
VTL/utils/VTL_encryptor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_encryptor.c.s
.PHONY : VTL/utils/VTL_encryptor.c.s

VTL/utils/VTL_file.o: VTL/utils/VTL_file.c.o
.PHONY : VTL/utils/VTL_file.o

# target to build an object file
VTL/utils/VTL_file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_file.c.o
.PHONY : VTL/utils/VTL_file.c.o

VTL/utils/VTL_file.i: VTL/utils/VTL_file.c.i
.PHONY : VTL/utils/VTL_file.i

# target to preprocess a source file
VTL/utils/VTL_file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_file.c.i
.PHONY : VTL/utils/VTL_file.c.i

VTL/utils/VTL_file.s: VTL/utils/VTL_file.c.s
.PHONY : VTL/utils/VTL_file.s

# target to generate assembly for a file
VTL/utils/VTL_file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_file.c.s
.PHONY : VTL/utils/VTL_file.c.s

VTL/utils/VTL_time.o: VTL/utils/VTL_time.c.o
.PHONY : VTL/utils/VTL_time.o

# target to build an object file
VTL/utils/VTL_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_time.c.o
.PHONY : VTL/utils/VTL_time.c.o

VTL/utils/VTL_time.i: VTL/utils/VTL_time.c.i
.PHONY : VTL/utils/VTL_time.i

# target to preprocess a source file
VTL/utils/VTL_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_time.c.i
.PHONY : VTL/utils/VTL_time.c.i

VTL/utils/VTL_time.s: VTL/utils/VTL_time.c.s
.PHONY : VTL/utils/VTL_time.s

# target to generate assembly for a file
VTL/utils/VTL_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/VTL_time.c.s
.PHONY : VTL/utils/VTL_time.c.s

VTL/utils/db/VTL_db_credentals.o: VTL/utils/db/VTL_db_credentals.c.o
.PHONY : VTL/utils/db/VTL_db_credentals.o

# target to build an object file
VTL/utils/db/VTL_db_credentals.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/db/VTL_db_credentals.c.o
.PHONY : VTL/utils/db/VTL_db_credentals.c.o

VTL/utils/db/VTL_db_credentals.i: VTL/utils/db/VTL_db_credentals.c.i
.PHONY : VTL/utils/db/VTL_db_credentals.i

# target to preprocess a source file
VTL/utils/db/VTL_db_credentals.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/db/VTL_db_credentals.c.i
.PHONY : VTL/utils/db/VTL_db_credentals.c.i

VTL/utils/db/VTL_db_credentals.s: VTL/utils/db/VTL_db_credentals.c.s
.PHONY : VTL/utils/db/VTL_db_credentals.s

# target to generate assembly for a file
VTL/utils/db/VTL_db_credentals.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/db/VTL_db_credentals.c.s
.PHONY : VTL/utils/db/VTL_db_credentals.c.s

VTL/utils/log/VTL_console_log.o: VTL/utils/log/VTL_console_log.c.o
.PHONY : VTL/utils/log/VTL_console_log.o

# target to build an object file
VTL/utils/log/VTL_console_log.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/log/VTL_console_log.c.o
.PHONY : VTL/utils/log/VTL_console_log.c.o

VTL/utils/log/VTL_console_log.i: VTL/utils/log/VTL_console_log.c.i
.PHONY : VTL/utils/log/VTL_console_log.i

# target to preprocess a source file
VTL/utils/log/VTL_console_log.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/log/VTL_console_log.c.i
.PHONY : VTL/utils/log/VTL_console_log.c.i

VTL/utils/log/VTL_console_log.s: VTL/utils/log/VTL_console_log.c.s
.PHONY : VTL/utils/log/VTL_console_log.s

# target to generate assembly for a file
VTL/utils/log/VTL_console_log.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/VTL/utils/log/VTL_console_log.c.s
.PHONY : VTL/utils/log/VTL_console_log.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/VTL.dir/build.make CMakeFiles/VTL.dir/main.c.s
.PHONY : main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... VTL"
	@echo "... VTL_img"
	@echo "... VTL_tests_Audio"
	@echo "... VTL/content_platform/VTL_content_platform_flags_check.o"
	@echo "... VTL/content_platform/VTL_content_platform_flags_check.i"
	@echo "... VTL/content_platform/VTL_content_platform_flags_check.s"
	@echo "... VTL/content_platform/VTL_content_platform_publication.o"
	@echo "... VTL/content_platform/VTL_content_platform_publication.i"
	@echo "... VTL/content_platform/VTL_content_platform_publication.s"
	@echo "... VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.o"
	@echo "... VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.i"
	@echo "... VTL/content_platform/infra/audio/VTL_audio_configs_for_gen_init.s"
	@echo "... VTL/content_platform/infra/audio/VTL_audio_gen.o"
	@echo "... VTL/content_platform/infra/audio/VTL_audio_gen.i"
	@echo "... VTL/content_platform/infra/audio/VTL_audio_gen.s"
	@echo "... VTL/content_platform/infra/text/VTL_publication_text_gen.o"
	@echo "... VTL/content_platform/infra/text/VTL_publication_text_gen.i"
	@echo "... VTL/content_platform/infra/text/VTL_publication_text_gen.s"
	@echo "... VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.o"
	@echo "... VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.i"
	@echo "... VTL/content_platform/infra/text/VTL_text_configs_for_gen_init.s"
	@echo "... VTL/content_platform/tg/VTL_content_platform_tg_net.o"
	@echo "... VTL/content_platform/tg/VTL_content_platform_tg_net.i"
	@echo "... VTL/content_platform/tg/VTL_content_platform_tg_net.s"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.o"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.i"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_audio.s"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.o"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.i"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_sub.s"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.o"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.i"
	@echo "... VTL/content_platform/tg/media_container_params/VTL_content_platform_tg_params_video.s"
	@echo "... VTL/media_container/audio/VTL_audio_data.o"
	@echo "... VTL/media_container/audio/VTL_audio_data.i"
	@echo "... VTL/media_container/audio/VTL_audio_data.s"
	@echo "... VTL/media_container/audio/infra/VTL_audio_read.o"
	@echo "... VTL/media_container/audio/infra/VTL_audio_read.i"
	@echo "... VTL/media_container/audio/infra/VTL_audio_read.s"
	@echo "... VTL/media_container/audio/infra/VTL_audio_write.o"
	@echo "... VTL/media_container/audio/infra/VTL_audio_write.i"
	@echo "... VTL/media_container/audio/infra/VTL_audio_write.s"
	@echo "... VTL/media_container/img/VTL_img_core.o"
	@echo "... VTL/media_container/img/VTL_img_core.i"
	@echo "... VTL/media_container/img/VTL_img_core.s"
	@echo "... VTL/media_container/img/VTL_img_filters.o"
	@echo "... VTL/media_container/img/VTL_img_filters.i"
	@echo "... VTL/media_container/img/VTL_img_filters.s"
	@echo "... VTL/media_container/img/VTL_img_utils.o"
	@echo "... VTL/media_container/img/VTL_img_utils.i"
	@echo "... VTL/media_container/img/VTL_img_utils.s"
	@echo "... VTL/media_container/video/VTL_video_data.o"
	@echo "... VTL/media_container/video/VTL_video_data.i"
	@echo "... VTL/media_container/video/VTL_video_data.s"
	@echo "... VTL/publication/VTL_publication.o"
	@echo "... VTL/publication/VTL_publication.i"
	@echo "... VTL/publication/VTL_publication.s"
	@echo "... VTL/publication/text/VTL_publication_markup_text_flags_check.o"
	@echo "... VTL/publication/text/VTL_publication_markup_text_flags_check.i"
	@echo "... VTL/publication/text/VTL_publication_markup_text_flags_check.s"
	@echo "... VTL/publication/text/VTL_publication_text_data.o"
	@echo "... VTL/publication/text/VTL_publication_text_data.i"
	@echo "... VTL/publication/text/VTL_publication_text_data.s"
	@echo "... VTL/publication/text/VTL_publication_text_op.o"
	@echo "... VTL/publication/text/VTL_publication_text_op.i"
	@echo "... VTL/publication/text/VTL_publication_text_op.s"
	@echo "... VTL/publication/text/infra/VTL_publication_text_read.o"
	@echo "... VTL/publication/text/infra/VTL_publication_text_read.i"
	@echo "... VTL/publication/text/infra/VTL_publication_text_read.s"
	@echo "... VTL/publication/text/infra/VTL_publication_text_write.o"
	@echo "... VTL/publication/text/infra/VTL_publication_text_write.i"
	@echo "... VTL/publication/text/infra/VTL_publication_text_write.s"
	@echo "... VTL/user/VTL_user_data.o"
	@echo "... VTL/user/VTL_user_data.i"
	@echo "... VTL/user/VTL_user_data.s"
	@echo "... VTL/user/history/VTL_user_history_data.o"
	@echo "... VTL/user/history/VTL_user_history_data.i"
	@echo "... VTL/user/history/VTL_user_history_data.s"
	@echo "... VTL/user/history/db/VTL_user_history_save.o"
	@echo "... VTL/user/history/db/VTL_user_history_save.i"
	@echo "... VTL/user/history/db/VTL_user_history_save.s"
	@echo "... VTL/utils/VTL_encryptor.o"
	@echo "... VTL/utils/VTL_encryptor.i"
	@echo "... VTL/utils/VTL_encryptor.s"
	@echo "... VTL/utils/VTL_file.o"
	@echo "... VTL/utils/VTL_file.i"
	@echo "... VTL/utils/VTL_file.s"
	@echo "... VTL/utils/VTL_time.o"
	@echo "... VTL/utils/VTL_time.i"
	@echo "... VTL/utils/VTL_time.s"
	@echo "... VTL/utils/db/VTL_db_credentals.o"
	@echo "... VTL/utils/db/VTL_db_credentals.i"
	@echo "... VTL/utils/db/VTL_db_credentals.s"
	@echo "... VTL/utils/log/VTL_console_log.o"
	@echo "... VTL/utils/log/VTL_console_log.i"
	@echo "... VTL/utils/log/VTL_console_log.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

